---
title: "p8105_hw3_yz5248"
author: "yz5248"
date: "2025-10-05"
output: github_document
---

```{r}
library(p8105.datasets)
library(readr)
library(tidyverse)  
library(scales)      
library(knitr)
library(lubridate)
library(janitor)
library(patchwork)
library(ggplot2)
theme_set(theme_minimal(base_size = 14))
data("instacart")
```

#Problem 1
```{r}
n_aisles = 
  instacart |>
  distinct(aisle_id, aisle) |>
  nrow()
n_aisles   

aisle_counts = 
  instacart |>
  count(aisle, sort = TRUE) |>
  rename(n_orders = n)

aisle_counts |>
  slice_head(n = 20) |> 
  knitr::kable()
```

```{r}
aisle_counts |> 
  filter(n_orders > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n_orders)) |> 
  ggplot(aes(x = aisle, y = n_orders)) +
  geom_col(fill = "blue") +
  coord_flip() +
  scale_y_continuous(labels = comma) +
  labs(
    title = "Aisles with more than 10,000 items ordered",
    x = "Aisle",
    y = "Number of items ordered"
  ) +
  theme_minimal(base_size = 13)

```

```{r}
target_aisles = c("baking ingredients", "dog food care", "packaged vegetables fruits")

top3_items = 
  instacart |> 
  filter(aisle == target_aisles) |> 
  count(aisle, product_name, sort = TRUE) |> 
  group_by(aisle) |> 
  slice_head(n = 3) |> 
  ungroup()

top3_items |> 
  kable()
```

```{r}
weekday_labels = c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday")

mean_hour = 
  instacart |>
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream")) |>
  group_by(product_name, order_dow) |>
  summarise(mean_hour = mean(order_hour_of_day), .groups = "drop") |>
  mutate(weekday = factor(order_dow, levels = 0:6, labels = weekday_labels)) |>
  select(product_name, weekday, mean_hour) |>
  pivot_wider(names_from = weekday, values_from = mean_hour)

mean_hour |>
  mutate(across(where(is.numeric), ~round(., 1))) |>
  kable()
```


#Problem 2
```{r}
Zip_Codes = 
  read_csv("zillow_data/Zip Codes.csv") |>
  janitor::clean_names()

Zip_zori = 
  read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |>
  janitor::clean_names()
view(Zip_zori)
```

```{r}
rent_df =
  Zip_zori |>
  select(region_name, starts_with("x")) |>   
  rename(zip = region_name) |>
  pivot_longer(
    cols = starts_with("x"),
    names_to = "month_raw",
    values_to = "rent"
  ) |>
  mutate(
    month = str_remove(month_raw, "^x"),
    month = str_replace_all(month, "_", "-"),
    month = ymd(month),
    zip = as.character(zip),
    rent = as.numeric(rent)
  ) |>
  select(zip, month, rent) |>
  drop_na(rent)

view(rent_df)
```

```{r}
zip_df = 
  Zip_Codes |> 
  transmute(                      
    zip = as.character(zip_code), 
    borough = case_when(          
      str_detect(county, "New York") ~ "Manhattan",
      str_detect(county, "Kings") ~ "Brooklyn",
      str_detect(county, "Queens") ~ "Queens",
      str_detect(county, "Bronx") ~ "Bronx",
      str_detect(county, "Richmond") ~ "Staten Island",
      TRUE ~ "Other"
    )
  )

```

```{r}
rent_tidy = 
  left_join(rent_df, zip_df, by = "zip") |>
  rename(Year = month) |>
  view()
```

```{r}
rent_summary =
  rent_tidy |>
  mutate(Year = year(Year)) |>    
  group_by(borough, Year) |>
  summarise(mean_rent = mean(rent, na.rm = TRUE)) |>
  arrange(borough, Year) 

rent_summary |>
  knitr::kable(
    caption = "Average Rental Price by Borough and Year (Zillow ZORI Data)",
    digits = 0
  ) 

```

make a plot
```{r}
plot_trend <- ggplot(rent_tidy, aes(x = Year, y = rent, group = zip)) +
  geom_line(aes(color = borough), alpha = 0.3, size = 0.6) +
  facet_wrap(~ borough, scales = "free_y") +  
  labs(
    title = "NYC Rental Prices by ZIP Code and Borough (Zillow ZORI Data)",
    x = "Year",
    y = "Rental Price (USD)",
    color = "Borough"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold", size = 13)
  )
plot_trend
```

About 2023
```{r}
rent_2023 <- rent_tidy |>
  filter(year(Year) == 2023)


zip_mean_2023 <- rent_2023 |>
  group_by(borough, zip) |>
  summarise(mean_rent = mean(rent, na.rm = TRUE), .groups = "drop")|>
  ggplot(aes(x = borough, y = mean_rent, fill = borough)) +
  geom_boxplot(alpha = 0.8, outlier.color = "red", outlier.shape = 1) +
  geom_jitter(width = 0.2, alpha = 0.4, color = "black") + 
  labs(
    title = "Distribution of Average ZIP-Code-Level Rents in 2023",
    subtitle = "Comparison across NYC boroughs (Zillow ZORI Data)",
    x = "Borough",
    y = "Average Monthly Rent (USD)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 13),
    axis.text.x = element_text(face = "bold")
  )
zip_mean_2023
```

```{r}
combined_plot <- plot_trend / zip_mean_2023 +
  plot_annotation(
    title = "NYC Rental Prices: Trends and 2023 Distributions",
    theme = theme(plot.title = element_text(face = "bold", size = 18))
  )

combined_plot

ggsave("results/nyc_rental_combined_plot.png",
       combined_plot,
       width = 12, height = 10, dpi = 300)
```


#Problem 3
```{r}
nhanes_accel <- read_csv("nhanes_accel.csv") |> 
  clean_names()

nhanes_accel <- read_csv("nhanes_accel.csv") |> 
  clean_names()

```

